### ISSUE TITLE
Ansi text

### ISSUE THREAD

**Issue by limelect** [delphidabbler/delphi-tips#31]
On D10.2.3 I had problems when pressing TV to see the text file.
So I had to change a few places to ANSI
If you want my source get in touch or tell me where to send it?

**Comment by delphidabbler** [comment]
Thx for reporting this, and for offering your code.

There are two straightforward ways to send me the code. Both involve commenting on this issue below.

1. If you are viewing this site on a PC I think there should be a message below the comment box where you can drag and drop the source file. I'm a bit vague about where exactly because I'm typing this on my tablet and the interface is different!

2. You could simply copy and paste your code into the comment. If you enclose the code in backticks like I show below that will make it much easier for me to read & copy. (Adding `pascal` after the opening backticks will highlight the code)

        ```pascal
        
        Paste your code here
        
        ```
Thanks

**Comment by delphidabbler** [comment]
Oh yes, one more thing.

Which tip does this relate to please? The tip number would be best - it's at the end of the tip page's URL: `https://delphidabbler.github.io/delphi-tips/tips/<tip-number>`

**Comment by limelect** [comment]
[MainUnit.zip](https://github.com/delphidabbler/delphi-tips/files/7273251/MainUnit.zip)
Just the pas file. to find changes compare files

**Comment by delphidabbler** [comment]
Hi

This is _Delphi Tips Manager:_

    Delphi Tips Manager v1.0
    Copyright (C) 2009 by Kachwahed 

It's nothing to do with this tips website and I don't maintain it. We've had this misunderstanding last year too - see issues #1 and #2 

So, sorry, but there's nothing I can do with this.
